name: Docker Image CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        run: nc -zv ${{ secrets.HOST }} ${{ secrets.PORT }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Compose Overwrite
        run: |
          echo 'services:' > docker-compose.yml
          echo '  redirect:' >> docker-compose.yml
          echo '    image: ghcr.io/${{ github.repository }}:${{ github.sha }}' >> docker-compose.yml
          echo '    environment:' >> docker-compose.yml
          echo '      - PORT=80' >> docker-compose.yml
          echo '    labels:' >> docker-compose.yml
          echo '      - traefik.enable=true' >> docker-compose.yml
          echo '      - traefik.http.routers.${{ github.ref_name }}-redirect.rule=Host(`${{ secrets.DOMAIN }}`)' >> docker-compose.yml
          echo '      - traefik.http.services.${{ github.ref_name }}-redirect.loadbalancer.server.port=80' >> docker-compose.yml
          echo '      - traefik.http.routers.${{ github.ref_name }}-redirect.entrypoints=websecure' >> docker-compose.yml
          echo '      - traefik.http.routers.${{ github.ref_name }}-redirect.tls.certresolver=${{ secrets.CERT_RESOLVER }}' >> docker-compose.yml
          echo '      - traefik.docker.network=traefik_network' >> docker-compose.yml
          echo 'networks:' >> docker-compose.yml
          echo '  traefik_network:' >> docker-compose.yml
          echo '    external: true' >> docker-compose.yml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: https://ghcr.io
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: copy files via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yml,docker-compose.yml"
          target: /home/enydyne/redirect
          rm: true
          debug: true
          overwrite: true
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/enydyne/redirect
            export SERVER_TAG=${{ github.sha }}
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "tsukinoko-kun" --password-stdin
            docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            docker compose down --remove-orphans || true
            docker compose up -d
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DC_WEBHOOK }}
          content: "Deployed redirect image with tag ${{ github.sha }} to ${{ secrets.DOMAIN }}"
